text = "hello world"
d = dict.fromkeys(text, 0)
for c in text: d[c] += 1
h = (d ['h'])
e = (d ['e'])
l = (d ['l'])
o = (d ['o'])
w = (d ['w'])
r = (d ['r'])
d = (d ['d'])
print("h - {}".format (h))
print("e - {}".format (e))
print("l - {}".format (l))
print("o - {}".format (o))
print("w - {}".format (w))
print("r - {}".format (r))
print("d - {}".format (d))